### ISSUE TITLE
checking connection and forcing reconnection

### ISSUE THREAD

**Issue by waiot** [mobizt/Firebase-Arduino-WiFi101#6]
Hi, first of all, thanks for this amazing library.
I'm just wondering, how can I force a reconnection attempt as my project will lose connection and it will take up to 20 seconds to reconnect.
My project is interactive so when people use it, it uploads the data to firebase and a user waiting 20 seconds will make them walk away.
I am using Firebase.reconnectWiFi(true); but I would like to be able to monitor my connection and force it to reconnect when the connection is lost.

How would I check the connection status?
How can I force it to reconnect if disconnected?

thanks so much.

**Comment by mobizt** [comment]
The time interval for Firebase library to take care for the WiFi reconnection is every 10 seconds.

Why 10 seconds? Because this is the interval to prevent the mcu to wait all the time (blocking operation) if the WiFi can't connect all the times and if the wait timeout reached (approx. 5 seconds), exit the wait loop.

The WiFi connection can't be handle directly as ESP chip but through WiFi101 library which control the communication process with ATWINC1500 WiFi chip.

If you don't want the wait in Firebase library, you should check the WiFi status and reconnect by yourself before call the Firebase functions and in the loop too.


As a [example](https://github.com/arduino-libraries/WiFi101/blob/master/examples/WiFiSSLClient/WiFiSSLClient.ino) from WiFi101 library, you still need to wait for WiFi to establish.
